export const SUBMIT_NAME = 'SUBMIT_NAME';
export const SUBMIT_EMAIL = 'SUBMIT_EMAIL';
export const SUBMIT_REPASSWORD = 'SUBMIT_REPASSWORD';
export const SUBMIT_PASSWORD = 'SUBMIT_PASSWORD';

export const SUBMIT_LOGNAME = 'SUBMIT_LOGNAME';
export const SUBMIT_LOGPASSWORD = 'SUBMIT_LOGPASSWORD';

 

